-- tutorial stuff
return {
  require 'tutorial.basic',
  --require 'tutorial.nand',
  -- require 'tutorial.wire',
  -- require 'tutorial.not',
  -- require 'tutorial.and',
  -- require 'tutorial.or',
  -- require 'tutorial.xor',
  -- require 'tutorial.mux',
  require 'tutorial.demux',
  require 'tutorial.decoder',
  require 'tutorial.posint',
  require 'tutorial.negint',
  require 'tutorial.addition',
  require 'tutorial.subtraction',
  require 'tutorial.comparator',
  require 'tutorial.shifter',
  require 'tutorial.srlatch',
  require 'tutorial.dlatch',
  require 'tutorial.dflipflop',
  require 'tutorial.synchronous',
  require 'tutorial.meminit',
  require 'tutorial.propdelay',
}
