-- Circuitopedia stuff
return {
  require 'ctpd.basic',
  require 'ctpd.nand',
  require 'ctpd.wire',
  require 'ctpd.not',
  require 'ctpd.and',
  require 'ctpd.or',
  require 'ctpd.xor',
  require 'ctpd.mux',
  require 'ctpd.demux',
  require 'ctpd.decoder',
  require 'ctpd.posint',
  require 'ctpd.negint',
  require 'ctpd.addition',
  require 'ctpd.subtraction',
  require 'ctpd.comparator',
  require 'ctpd.shifter',
  require 'ctpd.srlatch',
  require 'ctpd.dlatch',
  require 'ctpd.dflipflop',
  require 'ctpd.synchronous',
  require 'ctpd.meminit',
  require 'ctpd.propdelay',
}
