
add_group({
  name=T.memory1_name,
  id='memory1',
  icon='campaign_memory1.png',
  desc=T.memory1_desc,
})

easy_add_level2({
  id="latch_door",
  group='memory1',
  deps={},
  extra_text= {
    {
      title=T.latch_door_think_title,
      text=T.latch_door_think_text,
    },
    {wiki='srlatch'},
  }
})

easy_add_level2({
  id="dlatch",
  group='memory1',
  deps={},
  extra_text= {
    {
      title=T.dlatch_example_title,
      text=T.dlatch_example_text,
    },
    {wiki='dlatch'},
    {
      title=T.dlatch_symbol_title,
      scale=4,
      img='wiki/mem2.png',
    },
    {
      title=T.dlatch_truthtable_title,
      scale=4,
      img='wiki/mem3.png',
    },
    {
      title=T.dlatch_impl_title,
      scale=4,
      img='wiki/mem4.png',
    },
  }
})

easy_add_level2({
  id="photo",
  group='memory1',
  deps={},
  extra_text= {
    {
      title=T.photo_analogy_title,
      text=T.photo_analogy_text,
    },
    {wiki='dflipflop'},
  }
})

easy_add_level2({
  id="combo_detector",
  group='memory1',
  deps={},
  extra_text= {
    {
      title=T.combo_detector_clock_title,
      text=T.combo_detector_clock_text,
    },
    {
      title=T.combo_detector_timing_title,
      text=T.combo_detector_timing_text,
    },
    {
      title=T.combo_detector_delay_title,
      text=T.combo_detector_delay_text,
    },
    {
      title=T.combo_detector_history_title,
      text=T.combo_detector_history_text,
    },
    {
      title=T.combo_detector_output_title,
      text=T.combo_detector_output_text,
    },
    {wiki='propdelay'},
    {wiki='setuphold'},
  }
})

easy_add_level2({
  id="dflipflop_with_enable",
  group='memory1',
  deps={},
  extra_text= {
    {
      title=T.dflipflop_with_enable_hint_title,
      text=T.dflipflop_with_enable_hint_text,
    },
    {
      title=T.dflipflop_with_enable_example_title,
      text=T.dflipflop_with_enable_example_text,
    },
    {
      title=T.dflipflop_with_enable_tests_title,
      text=T.dflipflop_with_enable_tests_text,
    },
    {
      title=T.dflipflop_with_enable_comment_title,
      text=T.dflipflop_with_enable_comment_text,
    },
    {
      title=T.dflipflop_with_enable_schema_title,
      img='levels/D_with_enable.png',
      scale=4,
    },
    {wiki='dflipflop'},
  }
})

easy_add_level2({
  id="dff_w_r",
  group='memory1',
  deps={},
  extra_text= {
    {
      title=T.dff_w_r_hint_title,
      text=T.dff_w_r_hint_text,
    },
    {
      title=T.dff_w_r_comment_title,
      text=T.dff_w_r_comment_text,
    },
    {
      title=T.dff_w_r_schema_title,
      img='levels/D_with_reset.png',
      scale=4,
    },
    {
      title=T.dff_w_r_tests_title,
      text=T.dff_w_r_tests_text,
    },
    {wiki='dflipflop'},
  }
})

easy_add_level2({
  id="register4",
  group='memory1',
  deps={},
  extra_text= {
    {
      title=T.register4_hint_title,
      text=T.register4_hint_text,
    },
    {
      title=T.register4_tests_title,
      text=T.register4_tests_text,
    },
    {wiki='dflipflop'},
  }
})

easy_add_level2({
  id="registerfile",
  group='memory1',
  deps={},
  extra_text= {
    {
      title=T.registerfile_hint_title,
      text=T.registerfile_hint_text,
    },
    {
      title=T.registerfile_tests_title,
      text=T.registerfile_tests_text,
    },
    {wiki='dflipflop'},
    {wiki='demux'},
  }
})

easy_add_level2({
  id="npu1",
  group='memory1',
  deps={},
  extra_text= {
    {
      title=T.npu1_data_title,
      text=T.npu1_data_text,
    },
    {
      title=T.npu1_asm_title,
      text=T.npu1_asm_text,
    },
    {
      title=T.npu1_prog_title,
      text=T.npu1_prog_text,
    },
    {wiki='synchronous'},
  }
})
