IF (STEAM)
  include_directories(${CMAKE_SOURCE_DIR}/third_party/steam/)
  add_compile_definitions(WITH_STEAM=1)
  IF (WIN32)
    link_directories(${CMAKE_SOURCE_DIR}/third_party/redistributable_bin/win64/)
    SET(steam_libs steam_api64)
  ELSEIF (APPLE)
    link_directories(${CMAKE_SOURCE_DIR}/third_party/redistributable_bin/osx/)
    SET(steam_libs steam_api)
  ELSEIF (UNIX AND NOT APPLE)
    IF (CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
      link_directories(${CMAKE_SOURCE_DIR}/third_party/redistributable_bin/linuxarm64/)
    ELSEIF (CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
      link_directories(${CMAKE_SOURCE_DIR}/third_party/redistributable_bin/linux64/)
    ELSE()
      link_directories(${CMAKE_SOURCE_DIR}/third_party/redistributable_bin/linux32/)
    ENDIF()
    SET(steam_libs steam_api)
  ENDIF()
ENDIF()
